name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Récupère le code de ton dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2: Se connecte à Docker Hub
    # On utilise les nouveaux secrets DOCKERHUB_*
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Étape 3: Extrait les métadonnées pour l'image Docker
    # Le nom de l'image est maintenant au format Docker Hub
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/linkarr
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch

    # Étape 4: Construit et pousse l'image (cette étape ne change pas)
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}